---
title: "Age-Analysis"
output: html_document
date: "2022-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(ggpubr)
library(ggpmisc)
```

```{r}
train_data <- read_csv("./train.csv", show_col_types = FALSE)
test_data <- read_csv("./test.csv", show_col_types = FALSE)
```

```{r}
train_data |>
  select(Age, Survived,Sex) |>
  mutate(number = 1) |>
  group_by(Age) |>
  drop_na() |>
  summarise(age_survival = sum(Survived)/sum(number),.groups = 'drop') |>
  mutate(age_group = case_when(Age >= 0 & Age < 10 ~ "Age Group 0-10",
                               Age >= 10 & Age < 20 ~ "Age Group 10-20",
                               Age >= 20 & Age < 30 ~ "Age Group 20-30",
                               Age >= 30 & Age < 40 ~ "Age Group 30-40",
                               Age >= 40 & Age < 50 ~ "Age Group 40-50",
                               Age >= 50 & Age < 60 ~ "Age Group 50-60",
                               Age >= 60 ~ "Age Group 60+"))|>
  filter(age_group == "Age Group 0-10" |
         age_group == "Age Group 10-20"|
         age_group == "Age Group 20-30"|
         age_group == "Age Group 30-40")|>
  ggplot(aes(x = Age, y = age_survival))+
  geom_line(alpha = 0.1)+
  facet_wrap(~age_group,nrow = 4)+
  stat_smooth(method = 'lm', formula = y ~ poly(x, 3, raw = TRUE), se = FALSE)+
  geom_point(alpha = 0.1)+
   stat_poly_eq(aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~")),
    formula = y ~ poly(x, 3, raw = TRUE)) 



train_data |>
  select(Age, Survived,Sex) |>
  mutate(number = 1) |>
  group_by(Age) |>
  drop_na() |>
  summarise(age_survival = sum(Survived)/sum(number),.groups = 'drop') |>
  mutate(age_group = case_when(Age >= 0 & Age < 10 ~ "Age Group 0-10",
                               Age >= 10 & Age < 20 ~ "Age Group 10-20",
                               Age >= 20 & Age < 30 ~ "Age Group 20-30",
                               Age >= 30 & Age < 40 ~ "Age Group 30-40",
                               Age >= 40 & Age < 50 ~ "Age Group 40-50",
                               Age >= 50 & Age < 60 ~ "Age Group 50-60",
                               Age >= 60 ~"Age Group 60+"))|>
  filter(age_group == "Age Group 40-50"|
         age_group == "Age Group 50-60" |
         age_group == "Age Group 60+" )|>
  ggplot(aes(x = Age, y = age_survival))+
  geom_line(alpha = 0.1)+
  stat_smooth(method = 'lm', formula = y ~ poly(x, 3, raw = TRUE), se = FALSE)+
  geom_point(alpha = 0.1)+
  facet_wrap(~age_group, nrow = 3)+
   stat_poly_eq(aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~")),
    formula = y ~ poly(x, 3, raw = TRUE)) 

  
```   


```{r}
groups = list("Age Group 0-10","Age Group 10-20","Age Group 20-30","Age Group 30-40","Age Group 40-50","Age Group 50-60","Age Group 60+")

for (x in groups) {
  print(train_data |>
  select(Age, Survived,Sex) |>
  mutate(number = 1) |>
  group_by(Age) |>
  drop_na() |>
  summarise(age_survival = sum(Survived)/sum(number),.groups = 'drop') |>
  mutate(age_group = case_when(Age >= 0 & Age < 10 ~ "Age Group 0-10",
                               Age >= 10 & Age < 20 ~ "Age Group 10-20",
                               Age >= 20 & Age < 30 ~ "Age Group 20-30",
                               Age >= 30 & Age < 40 ~ "Age Group 30-40",
                               Age >= 40 & Age < 50 ~ "Age Group 40-50",
                               Age >= 50 & Age < 60 ~ "Age Group 50-60",
                               Age >= 60 ~"Age Group 60+"))|>
    filter(age_group == x)|>
    ggplot(aes(x = Age, y = age_survival))+
  geom_line(alpha = 0.1)+
  stat_smooth(method = 'lm', formula = y ~ poly(x, 2, raw = TRUE), se = FALSE)+
  geom_point(alpha = 0.1)+
   stat_poly_eq(aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~")),
    formula = y ~ poly(x, 2, raw = TRUE),inherit.aes = TRUE))
}
```



```{r}
train_data
```

