---
title: "test-model"
output: html_document
date: "2022-09-01"
---
-
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(ggpubr)
library(ggpmisc)
```

```{r}
train_data <- read_csv("./train.csv", show_col_types = FALSE)
test_data <- read_csv("./test.csv", show_col_types = FALSE)
```

```{r}
A_model1 <- 0.74 - 0.73*Age - 0.087*(Age)^2 - 0.3*(Age)^3 + 0.38*(Age)^4 - 0.55*(Age)^5

A_model2 <- 0.46 - 0.023*Age - 0.45*(Age)^2 + 0.53*(Age)^3 - 0.28*(Age)^4 - 0.18*(Age)^5
 
A_model3 <- 0.25 + 0.17*Age - 0.11*(Age)^2 - 0.043*(Age)^3 - 0.1*(Age)^4 + 0.089*(Age)^5

A_model4 <- 0.34 - 0.045*Age - 0.048*(Age)^2 + 0.23*(Age)^3 + 0.0057*(Age)^4 - 0.14*(Age)^5

A_model5 <- 2*10^5 - 22000*Age + 990*(Age)^2 - 22*(Age)^3 + 0.25*(Age)^4 - 0.0011*(Age)^5

A_model6 <- 9.1*10^5 - 8.3*Age + 3100*(Age)^2 - 56*(Age)^3 + 0.52*(Age)^4 - 0.0019*(Age)^5

A_model7 <- -37000 + 2700*Age - 78*(Age)^2 + 1.1*(Age)^3 - 0.008*(Age)^4 + 2.3*10^(-5)*(Age)^5
```


```{r}
test_data_final <- test_data |>
  select(PassengerId, Pclass, Sex, Age, Fare, Embarked) |>
  mutate(S_model = case_when(Sex == "female" ~ 0.74203,
                             Sex == "male" ~ 0.18891)) |>
  mutate(E_model = case_when(Embarked == "C" ~ 0.5535714,
                             Embarked == "Q" ~ 0.38961,
                             Embarked == "S" ~ 0.336956,
                             Embarked == NA ~ 1)) |>
  mutate(P_model = case_when(Pclass == 1 ~ 0.6296296,
                             Pclass == 2 ~ 0.4728261,
                             Pclass == 3 ~ 0.2423625)) |>
  mutate(A_model = case_when(Age >= 0 & Age < 10 
                             ~ 1.6 - 1.2*(Age) + 0.49*(Age^2) - 0.074*(Age^3) + 0.0036*(Age^4)  ,
                               Age >= 10 & Age < 20 
                             ~ -30.3 + 6.41*(Age) - 0.433*(Age^2) + 0.00953*(Age^3),
                               Age >= 20 & Age < 30 
                             ~ 8.17 - 1.11*(Age) + 0.0503*(Age^2) - 0.000741*(Age^3),
                               Age >= 30 & Age < 40 
                             ~ -151.49+13.3*(Age)-0.3863*(Age^{2})+0.00372*(Age^{3}),
                               Age >= 40 & Age < 50 
                             ~ -446.75+30.78*Age-0.704*Age^{2}+0.00535*Age^{3},
                               Age >= 50 & Age < 60 
                             ~ -22.7+0.891*Age-0.00856*Age^{2},
                               Age >= 60 
                             ~ 35.9 -1.04*(Age) + 0.00757*(Age^2))) 
         
test_data_final[is.na(test_data_final)]=0
  
```

